{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
{% set PKG_NAME = 'arduino-helpers' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}
package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

build:
  # If this is a new build for the same version, increment the build number.
  # If you do not include this key, it defaults to 0.
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python >=3.6
    - path-helpers
    - serial-device
    - numpy
    - pandas

  run:
    - python >=3.8
    - path-helpers
    - serial-device
    - numpy
    - pandas

test:
  imports:
    - {{ MODULE_NAME }}
    - {{ MODULE_NAME }}._version
    - {{ MODULE_NAME }}.bin.upload
    - {{ MODULE_NAME }}.context
    - {{ MODULE_NAME }}.hardware.arduino
    - {{ MODULE_NAME }}.hardware.boards
    - {{ MODULE_NAME }}.hardware.platform
    - {{ MODULE_NAME }}.hardware.teensy.adc
    - {{ MODULE_NAME }}.hardware.teensy.dma
    - {{ MODULE_NAME }}.hardware.teensy.pdb
    - {{ MODULE_NAME }}.hardware.teensy.pit
    - {{ MODULE_NAME }}.hardware.teensy.sim
    - {{ MODULE_NAME }}.hardware.tools
    - {{ MODULE_NAME }}.upload

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  summary: Helper functions for reading configs, etc. from an installed Arduino directory.
  license: GPLv2

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
#  git_url: ../
  path: ..
