{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
package:
  name: arduino-helpers
  version: {{ GIT_VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  #: .. versionadded:: 0.6
  noarch: true

requirements:
  build:
    - path_helpers
    #: .. versionchanged:: 0.6
    - python {{ python }}
    - serial-device
    #: .. versionadded:: 0.6
    - six

  run:
    - path_helpers
    #: .. versionchanged:: 0.6
    - python {{ python }}
    - serial-device
    #: .. versionadded:: 0.6
    - six

#: .. versionadded:: 0.6
test:
  imports:
    - arduino_helpers
    - arduino_helpers._version
    - arduino_helpers.bin.upload
    - arduino_helpers.context
    - arduino_helpers.hardware.arduino
    - arduino_helpers.hardware.boards
    - arduino_helpers.hardware.platform
    - arduino_helpers.hardware.teensy.adc
    - arduino_helpers.hardware.teensy.dma
    - arduino_helpers.hardware.teensy.pdb
    - arduino_helpers.hardware.teensy.pit
    - arduino_helpers.hardware.teensy.sim
    - arduino_helpers.hardware.tools
    - arduino_helpers.upload

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../
